<?php
// $Id: magazine_overrides.install,v 1.10.4.4 2009/06/17 15:03:07 njt1982 Exp $

/**
 * @file
 * The install file for Page Title allows the module to install (and uninstall) itself. This is required as this module uses its own table.
 */

/**
 * Implementation of hook_install().
 */
function magazine_overrides_install() {
}


/**
 * Implementation of hook_schema().
 */


/**
 * Implementation of hook_uninstall().
 */
function magazine_overrides_uninstall() {
}
