<?php
// $Id: hose_xml_view.module,v 1.1 2010/11/15 15:19:44 rayvaughn Exp $

/**
 * @file
 * Implementation of 'view' tag type.
 */

/**
 * @defgroup hose_xml_view view
 * @{
 * view field type plug-in.
 */

/**
 * Implementation of hook_hose_xml_field_name().
 */
function hose_xml_view_hose_xml_field_name() {
  return array('view' => t('view'));
} // hose_xml_view_hose_xml_field_name

/**
 * Implementation of hook_hose_xml_field_icon().
 */
function hose_xml_view_hose_xml_field_icon() {
  return drupal_get_path('module', 'hose_xml_view') .'/view.png';
} // hose_xml_view_hose_xml_field_icon

/**
 * Implementation of hook_hose_xml_settings_information().
 */
function hose_xml_view_hose_xml_settings_information() {
  return array(
    'hint_view' => array(
      'title' => t('Validation Hint'),
      'description' => t("(Optional) Enter a validation hint, specific to this export profile which will appear instead of the generic error message on export failure."),
    ),
  );
} // hose_xml_view_hose_xml_settings_information

/**
 * Implementation of hook_hose_xml_validate().
 */
function hose_xml_view_hose_xml_validate($data, $settings) {
  $reason = '';
  if (!empty($data)) {
    $reason = $settings['hint_view'] ? $settings['hint_view'] : t('Containers are tags that contain other tags but should not take any input except (optionally) attributes.');
  }
  return array(
    'data' => $data,
    'reason' => $reason,
  );
} // hose_xml_view_hose_xml_validate

/**
 * @} End of "defgroup hose_xml_view".
 */