<?php

/**
 * @file
 * Implementation of 'sandwich' tag type.
 */

/**
 * @defgroup hose_xml_sandwich Sandwich
 * @{
 * Sandwich field type plug-in.
 */

/**
 * Implementation of hook_hose_xml_field_name().
 */
function hose_xml_sandwich_hose_xml_field_name() {
  return array('sandwich' => t('Sandwich'));
} // hose_xml_sandwich_hose_xml_field_name

/**
 * Implementation of hook_hose_xml_field_icon().
 */
function hose_xml_sandwich_hose_xml_field_icon() {
  return drupal_get_path('module', 'hose_xml_sandwich') .'/sandwich.png';
} // hose_xml_sandwich_hose_xml_field_icon

/**
 * Implementation of hook_hose_xml_settings_information().
 */
function hose_xml_sandwich_hose_xml_settings_information() {
  return array(
    'hint_sandwich' => array(
      'title' => t('Validation Hint'),
      'description' => t("(Optional) Enter a validation hint, specific to this export profile which will appear instead of the generic error message on export failure."),
    ),
  );
} // hose_xml_sandwich_hose_xml_settings_information

/**
 * Implementation of hook_hose_xml_validate().
 */
function hose_xml_sandwich_hose_xml_validate($data, $settings) {
  $reason = '';
  if (!empty($data)) {
    $reason = $settings['hint_sandwich'] ? $settings['hint_sandwich'] : t('Containers are tags that contain other tags but should not take any input except (optionally) attributes.');
  }
  return array(
    'data' => $data,
    'reason' => $reason,
  );
} // hose_xml_sandwich_hose_xml_validate

/**
 * @} End of "defgroup hose_xml_sandwich".
 */