<?php

/**
 * @file
 * Implementation of 'alphanumeric' tag type.
 */

/**
 * @defgroup hose_xml_alphanumeric Alphanumeric
 * @{
 * Alphanumeric field type plug-in.
 *
 * Matches only alphanumeric characters (e.g. a-z A-Z 0-9)
 * and returns an export error on failure.
 */

/**
 * Implementation of hook_hose_xml_field_name().
 */
function hose_xml_alphanumeric_hose_xml_field_name() {
  return array('alphanumeric' => t('Alphanumeric'));
} // hose_xml_alphanumeric_hose_xml_field_name

/**
 * Implementation of hook_hose_xml_field_icon().
 */
function hose_xml_alphanumeric_hose_xml_field_icon() {
  return drupal_get_path('module', 'hose_xml_alphanumeric') .'/alphanumeric.png';
} // hose_xml_alphanumeric_hose_xml_field_icon

/**
 * Implementation of hook_hose_xml_settings_information().
 */
function hose_xml_alphanumeric_hose_xml_settings_information() {
  return array(
    'hint_alphanumeric' => array(
      'title' => t('Validation Hint'),
      'description' => t("(Optional) Enter a validation hint, specific to this export profile which will appear instead of the generic error message on export failure."),
    ),
  );
} // hose_xml_alphanumeric_hose_xml_settings_information

/**
 * Implementation of hook_hose_xml_validate().
 */
function hose_xml_alphanumeric_hose_xml_validate($data, $settings) {
  $reason = '';
  if (!ctype_alnum($data)) {
    $reason = $settings['hint_alphanumeric'] ? $settings['hint_alphanumeric'] : t('Entry contains invalid non-alphanumeric characters.');
  }
  return array(
    'data' => $data,
    'reason' => $reason,
  );
} // hose_xml_alphanumeric_hose_xml_validate

/**
 * @} End of "defgroup hose_xml_alphanumeric".
 */